delete from event_manager_db2.events;
alter table event_manager_db2.events auto_increment = 1;
insert into event_manager_db2.events(
  eventGroupId
 ,eventName
 ,eventCategory
 ,eventOverView
 ,scheduledStartDate
 ,expectedDeliveryDate
 ,fixedDeliveryDate
 ,expectedBillingDate
 ,customerCompany
 ,customerStaff
 ,progress
 ,eventStatus
 ,createdAt
 ,updatedAt) VALUES (
 1
 ,'装飾品シミュレーションシステム'
 ,1
 ,'装飾品シミュレーションシステム新規開発における開発支援'
 ,'2020/12/01'
 ,'2021/03/31'
 ,'2021/03/31'
 ,'2021/04/01'
 ,'今田株式会社'
 ,'今田昇'
 ,30
 ,1
 ,now()
 ,now());
insert into event_manager_db2.events(
  eventGroupId
 ,eventName
 ,eventCategory
 ,eventOverView
 ,scheduledStartDate
 ,expectedDeliveryDate
 ,fixedDeliveryDate
 ,expectedBillingDate
 ,customerCompany
 ,customerStaff
 ,progress
 ,eventStatus
 ,createdAt
 ,updatedAt) VALUES (
 1
 ,'装飾品販売ECサイト'
 ,1
 ,'装飾品販売サイト新規開発における開発支援'
 ,'2021/04/01'
 ,'2021/6/30'
 ,'2021/6/30'
 ,'2021/7/1'
 ,'今田株式会社'
 ,'今田昇'
 ,20
 ,1
 ,now()
 ,now());
insert into event_manager_db2.events(
  eventGroupId
 ,eventName
 ,eventCategory
 ,eventOverView
 ,scheduledStartDate
 ,expectedDeliveryDate
 ,fixedDeliveryDate
 ,expectedBillingDate
 ,customerCompany
 ,customerStaff
 ,progress
 ,eventStatus
 ,createdAt
 ,updatedAt) VALUES (
 1
 ,'SaaS連携システム'
 ,1
 ,'会計システムとの連携機能エンハンス'
 ,'2021/04/01'
 ,'2021/5/30'
 ,'2021/5/30'
 ,'2021/6/1'
 ,'明朗会計株式会社'
 ,'明朗明'
 ,30
 ,1
 ,now()
 ,now());
insert into event_manager_db2.events(
  eventGroupId
 ,eventName
 ,eventCategory
 ,eventOverView
 ,scheduledStartDate
 ,expectedDeliveryDate
 ,fixedDeliveryDate
 ,expectedBillingDate
 ,customerCompany
 ,customerStaff
 ,progress
 ,eventStatus
 ,createdAt
 ,updatedAt) VALUES (
 1
 ,'自治体向け税務システム'
 ,1
 ,'SpringMVCベースのWebアプリケーションにおけるコアな部分'
 ,'2021/06/01'
 ,'2021/11/30'
 ,'2021/11/30'
 ,'2021/12/1'
 ,'上位株式会社'
 ,'上位治'
 ,40
 ,4
 ,now()
 ,now());
insert into event_manager_db2.events(
  eventGroupId
 ,eventName
 ,eventCategory
 ,eventOverView
 ,scheduledStartDate
 ,expectedDeliveryDate
 ,fixedDeliveryDate
 ,expectedBillingDate
 ,customerCompany
 ,customerStaff
 ,progress
 ,eventStatus
 ,createdAt
 ,updatedAt) VALUES (
 1
 ,'医療機器メーカー向け病院スケジュール管理システム'
 ,2
 ,'病院様の医師情報等をWeb参照可能とするシステムの機能エンハンス'
 ,'2021/07/01'
 ,'2021/10/30'
 ,'2021/10/30'
 ,'2021/11/1'
 ,'セレクタ株式会社'
 ,'平野正明'
 ,100
 ,5
 ,now()
 ,now());
insert into event_manager_db2.events(
  eventGroupId
 ,eventName
 ,eventCategory
 ,eventOverView
 ,scheduledStartDate
 ,expectedDeliveryDate
 ,fixedDeliveryDate
 ,expectedBillingDate
 ,customerCompany
 ,customerStaff
 ,progress
 ,eventStatus
 ,createdAt
 ,updatedAt) VALUES (
 1
 ,'部品メーカー向けパーツ管理システム'
 ,2
 ,'部品調達に関する材料費含むコスト管理システム機能エンハンス'
 ,'2021/08/01'
 ,'2021/11/30'
 ,'2021/11/30'
 ,'2021/12/01'
 ,'帝国重工'
 ,'財前五郎'
 ,100
 ,6
 ,now()
 ,now());
