delete from event_manager_db.statuses;
alter table event_manager_db.statuses auto_increment = 1;
insert into event_manager_db.statuses(eventGroupId, name, createdAt, updatedAt) VALUES (1, '見積中', now(), now());
insert into event_manager_db.statuses(eventGroupId, name, createdAt, updatedAt) VALUES (1, '発注待ち', now(), now());
insert into event_manager_db.statuses(eventGroupId, name, createdAt, updatedAt) VALUES (1, '受注', now(), now());
insert into event_manager_db.statuses(eventGroupId, name, createdAt, updatedAt) VALUES (1, '納品済み', now(), now());
insert into event_manager_db.statuses(eventGroupId, name, createdAt, updatedAt) VALUES (1, '請求済み', now(), now());
insert into event_manager_db.statuses(eventGroupId, name, createdAt, updatedAt) VALUES (1, '入金確認済み', now(), now());
insert into event_manager_db.statuses(eventGroupId, name, createdAt, updatedAt) VALUES (1, '保留・中断', now(), now());
insert into event_manager_db.statuses(eventGroupId, name, createdAt, updatedAt) VALUES (1, '失注', now(), now());
